name: Deploy hello with echo

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      SSH_KEY:  ${{ secrets.SSH_PRIVATE_KEY }}
      TARGET_DIR: "/var/www/vicente/github-actions"

    steps:
      - name: Instalar OpenSSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Confiar en la huella del servidor
        run: |
          ssh-keyscan -v -p 22 "$VPS_HOST" >> ~/.ssh/known_hosts

      - name: Crear carpeta y escribir index.html con echo
        run: |
          REMOTE="$VPS_USER@$VPS_HOST"
          ssh -v -p 22 "$REMOTE" "
            mkdir -p '$TARGET_DIR' &&
            echo '<!doctype html><html lang=\"es\"><head><meta charset=\"utf-8\" /><title>Hola mundo</title></head><body><h1>¡Hola mundo!</h1></body></html>' > '$TARGET_DIR/index.html'
          "
