name: Deploy hello (appleboy)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: test env   # si usás Environment secrets

    steps:
      - name: Ejecutar comandos en el VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # tu privada (BEGIN/END)
          port: ${{ secrets.VPS_PORT || 22 }}
          script_stop: true
          # Opcional, mejor usar known_hosts reales; si no, deja esto en true para pruebas
          # fingerprint: ${{ secrets.VPS_HOST_FINGERPRINT }} 
          # host_verification: true
          script: |
            TARGET_DIR="/var/www/vicente/github-actions"
            sudo mkdir -p "$TARGET_DIR"
            echo '<!doctype html><html lang="es"><head><meta charset="utf-8" /><title>Hola mundo</title></head><body><h1>¡Hola mundo!</h1></body></html>' \
              | sudo tee "$TARGET_DIR/index.html" >/dev/null
